# Generated by Django 4.1 on 2025-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0006_alter_tareastable_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, verbose_name='Titulo del ticket')),
                ('start', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('description', models.TextField(verbose_name='Descripcion del problema')),
                ('status', models.CharField(max_length=20, verbose_name='Estado del ticket')),
                ('usuario', models.CharField(max_length=50, null=True, verbose_name='Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='tareasTable',
        ),
    ]
